use crate::account::ClientAccount;
use crate::error::PaymentError;
use std::io::Write;

pub struct AccountWriter<W: Write> {
    writer: csv::Writer<W>,
}

impl<W: Write> AccountWriter<W> {
    pub fn new(sink: W) -> Self {
        Self {
            writer: csv::Writer::from_writer(sink),
        }
    }

    pub fn write_accounts(
        &mut self,
        accounts: impl IntoIterator<Item = ClientAccount>,
    ) -> Result<(), PaymentError> {
        for account in accounts {
            self.writer.serialize(account)?;
        }
        self.writer.flush()?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;

    #[test]
    fn test_writer_output() {
        let mut buf = Vec::new();
        {
            let mut writer = AccountWriter::new(&mut buf);
            let account = ClientAccount {
                client: 1,
                available: dec!(1.5000),
                held: dec!(0.0000),
                total: dec!(1.5000),
                locked: false,
            };

            writer.write_accounts(vec![account]).unwrap();
        }
        let output = String::from_utf8(buf).unwrap();

        // CSV headers are generated by default with serde
        assert!(output.contains("client,available,held,total,locked"));
        // Check row (spacing doesn't matter as per requirements)
        assert!(
            output.contains("1,1.5,0.0,1.5,false")
                || output.contains("1,1.5000,0.0000,1.5000,false")
        );
    }
}
